version: '3.4'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  feddit:
    image: chasingcars/feddit:latest
    entrypoint: >
      sh -c "sleep 5 && python main.py"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:mysecretpassword@db:5432/postgres"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/version"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - "db:db"
    depends_on:
      - db
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "5050:5050"
    expose:
      - "5050"
    command: make run
    environment:
      FEDDIT_API_BASE_URL: "http://feddit:8080"
      JUPYTER_PLATFORM_DIRS: "1"
      HUGGINGFACE_API_KEY: "${HUGGINGFACE_API_KEY}"
